name: Build Project with Prebuilt Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull Docker image
      run: docker pull sejokim/qt_cross:latest

    - name: Ensure correct capitalization of CMakeLists.txt
      run: |
        docker run --rm --platform linux/arm64 -v ${{ github.workspace }}:/project -w /project sejokim/qt_cross:latest /bin/bash -c "
          if [ -f /project/CmakeLists.txt ]; then
            mv /project/CmakeLists.txt /project/CMakeLists.txt
          fi
        "

    - name: Build project inside Docker container
      run: |
        docker run --rm --platform linux/arm64 -v ${{ github.workspace }}:/project -w /project sejokim/qt_cross:latest /bin/bash -c "
          mkdir -p build && \
          find /project -mindepth 1 -maxdepth 1 ! -name build -exec cp -r {} build/ \; && \
          echo 'Contents of /project/build after copy:' && \
          ls -la /project/build && \
          echo 'Checking for CMakeLists.txt in build directory:' && \
          ls -l /project/build/CMakeLists.txt && \
          cd build && \
          cmake . && \
          make && \
          ldd InstrumentCluster
        "

    - name: Prepare artifacts
      run: |
        mkdir -p artifacts
        cp build/InstrumentCluster artifacts/
        cp -r src/*.qml src/*.qrc artifacts/
        cp -r drivers/libina219.so artifacts/
        cp -r utils/lastKnownCharge artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: artifacts